// <auto-generated />
namespace ERP.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class company_address2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(company_address2));
        
        string IMigrationMetadata.Id
        {
            get { return "201409201506458_company_address2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
